config/routes.rb
Rails.application.routes.draw do
  root 'searches#search'
  get '/searches' => 'searches#show'
end

app/models/api_parser.rb
class APIParser
  def self.find_issues(place, status, months_since=1)
    days_after = self.convert_to_days(months_since)
    days_before = days_after - 30
    request = Typhoeus::Request.new(
    "http://seeclickfix.com/api/v2/issues",
    params: {
      place_url: "#{place}",
      before: "#{(Date.today - days_before).to_s}",
      after: "#{(Date.today - days_after).to_s}",
      status: "#{status}",
      per_page: "1000"
    })
    self.hash_from(request, "issues")
  end

  def self.grab_location(address)
    request = Typhoeus::Request.new(
      "http://seeclickfix.com/api/v2/places",
      params: {
        address: address
      })
    response = self.hash_from(request, "places")
    response.first["url_name"]
  end

  def self.map_categories(issues)
    categories = {}.tap do |categories|
      issues.each do |issue|
        summary = issue["summary"]
        categories[summary] ||= 0
        categories[summary] += 1
      end
    end
    self.reduce_categories(categories)
  end

  def self.generate_dash_hash(categories)
    [].tap do |array|
      categories.each do |category, counter|
        array << { label: category, value: counter }
      end
    end
  end

  def self.generate_graph_data(place)
    time_frames = ["1","2","3","4"].reverse
    [].tap do |data|
      time_frames.each do |time_frame|
        month_value = Date.today.month - time_frame.to_i
        data << { x: month_value, y: find_issues(place, "open", time_frame).count }
      end
    end
  end

  def self.reduce_categories(hash)
    sorted = hash.sort_by { |k,v| v }.last(6).reverse
    {}.tap do |data|
      sorted.each do |sorted|
        data[sorted[0]] = sorted[1]
      end
    end
  end

  def self.convert_to_days(month)
    month.to_i * 30
  end

  def self.hash_from(request, api_type)
    JSON.parse(request.run.body)["#{api_type}"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
  end

  def show
    full_address = "#{params[:address]}, #{params[:city]}, #{params[:state]}"
    scf_location = APIParser.grab_location(full_address)

    if fields_missing?
      flash.now[:notice] = "Please fill in all fields"
      return render 'search' 
    elsif no_recent_issues_for(scf_location)
      flash.now[:notice] = "Sorry, there were no recent issues reported in this location."
      return render 'search'
    else
      update_dash_with(scf_location, full_address)
      redirect_to 'http://see-click-fix-dash.herokuapp.com/seeclickfix'
    end
  end

  private

  def fields_missing?
    params[:address].blank? || params[:city].blank? || params[:state].blank?
  end

  def no_recent_issues_for(address)
    open_issues = APIParser.find_issues(address, 'open')
    open_issues.blank?
  end

  def update_dash_with(address, full_address)
    open_issues = APIParser.find_issues(address, 'open')
    closed_issues = APIParser.find_issues(address, 'closed')
    acknowledged_issues = APIParser.find_issues(address, 'acknowledged')
    all_issues = open_issues + closed_issues + acknowledged_issues

    send_requests_for([open_issues, closed_issues, acknowledged_issues])
    update_dash('welcome', text: "#{full_address}")
    fetch_categories_for(all_issues)
    generate_graph_for(address)
  end

  def fetch_categories_for(all_issues)
    category_hash = APIParser.map_categories(all_issues)
    update_dash('categories', items: APIParser.generate_dash_hash(category_hash))
  end

  def generate_graph_for(address)
    data = APIParser.generate_graph_data(address)
    total_closed = 0
    data.each do |datum|
      total_closed += datum[:y]
    end
    update_dash('graph', points: data, displayedValue: total_closed / data.count)
  end

  def send_requests_for(data)
    dash_url = "http://see-click-fix-dash.herokuapp.com/widgets"
    data.each do |datum|
      status = datum.first["status"].downcase
      update_dash(status, current: datum.count)
    end
  end

  def update_dash(widget_name, request_hash)
    request_hash[:auth_token] = 'seeclickfix'
    dash_url = "http://see-click-fix-dash.herokuapp.com/widgets"
    Typhoeus.post("#{dash_url}/#{widget_name}", body: request_hash.to_json)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info alert-dismissable"
      when :success then "alert alert-success alert-dismissable"
      when :warning then "alert alert-warning alert-dismissable"
      when :alert then "alert alert-danger alert-dismissable"
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeeclickfixRouter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
  <% flash.each do |level, message| %>
    <div class="<%= flash_class(level) %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      <%= message %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/searches/search.html.erb
<div id="search-container">
  <div id="row">
    <h1>Search SeeClickFix: <br><small>see what’s being reported in your neighborhood</small></h1>
  </div>

  <div id="row">
    <div class="form-group" id="search-box">
        <%= form_tag searches_path, { :method => :get, :class => "form-inline" }  do %> 
          <%= label_tag :address, "Address:" %>
          <%= text_field_tag :address, "", :class => "form-control input-lg", :autofocus => true %><br>

          <%= label_tag :city, "City:" %>
          <%= text_field_tag :city, "", :class => "form-control input-lg" %><br>

          <%= label_tag :state, "State:" %>
          <%= text_field_tag :state, "", :class => "form-control input-lg" %><br><br>
          
          <%= submit_tag "Search", :class => "btn btn-lg btn-primary", :id => "search-button" %>
        <% end %>
    </div>
      <p id="notice">The search may take a little while. <br> Thanks for your patience!</p>
  </div>
</div>